# Copyright © 2025 Novatrax Labs LLC. All Rights Reserved.

"""
Pydantic schemas for API request/response models.
"""

from .common import (
    DetailedHealthResponse,
    ErrorResponse,
    HealthResponse,
    PaginationParams,
    ReadinessResponse,
    StatusResponse,
    SuccessResponse,
)
from .events import EventMessage, EventType
from .fixes import (
    Fix,
    FixApplyRequest,
    FixProposal,
    FixReviewRequest,
    FixStatus,
    RollbackRequest,
)
from .generator_schemas import (
    ClarificationChannel,
    ClarificationResponseRequest,
    ClarifyRequest,
    CodegenRequest,
    CritiqueRequest,
    DeployRequest,
    DocgenRequest,
    GenerationLanguage,
    GeneratorAuditQuery,
    GeneratorResponse,
    LLMConfigRequest,
    LLMProvider,
    LLMProviderStatus,
    PipelineRequest,
    TestgenRequest,
)
from .jobs import (
    GeneratedFile,
    GeneratorStatus,
    Job,
    JobCreateRequest,
    JobFilesResponse,
    JobListResponse,
    JobProgress,
    JobStage,
    JobStatus,
    LogEntry,
    LogsResponse,
    StageProgress,
)
from .omnicore_schemas import (
    CircuitBreakerResetRequest,
    CircuitBreakerStatus,
    DatabaseExportRequest,
    DatabaseQueryRequest,
    DeadLetterQueueQuery,
    MessageBusPublishRequest,
    MessageBusSubscribeRequest,
    MessageBusTopics,
    MessageRetryRequest,
    PluginInfo,
    PluginInstallRequest,
    PluginMarketplaceQuery,
    PluginReloadRequest,
    RateLimitConfigRequest,
)
from .sfe_schemas import (
    ArbiterCommand,
    ArbiterControlRequest,
    ArbiterStatus,
    ArenaCompetitionRequest,
    ArenaResult,
    BugAnalysisRequest,
    BugDetectionRequest,
    BugPrioritizationRequest,
    BugReport,
    CodebaseAnalysisReport,
    CodebaseAnalysisRequest,
    ComplianceCheckRequest,
    DLTAuditQuery,
    ImportFixRequest,
    KnowledgeGraphQuery,
    KnowledgeGraphUpdate,
    RLEnvironmentStatus,
    SandboxExecutionRequest,
    SIEMConfigRequest,
)

__all__ = [
    # Common
    "DetailedHealthResponse",
    "ErrorResponse",
    "HealthResponse",
    "PaginationParams",
    "ReadinessResponse",
    "StatusResponse",
    "SuccessResponse",
    # Jobs
    "GeneratedFile",
    "GeneratorStatus",
    "Job",
    "JobCreateRequest",
    "JobFilesResponse",
    "JobListResponse",
    "JobProgress",
    "JobStage",
    "JobStatus",
    "LogEntry",
    "LogsResponse",
    "StageProgress",
    # Events
    "EventMessage",
    "EventType",
    # Fixes
    "Fix",
    "FixApplyRequest",
    "FixProposal",
    "FixReviewRequest",
    "FixStatus",
    "RollbackRequest",
    # Generator
    "ClarificationResponseRequest",
    "ClarifyRequest",
    "CodegenRequest",
    "CritiqueRequest",
    "DeployRequest",
    "DocgenRequest",
    "GenerationLanguage",
    "GeneratorAuditQuery",
    "GeneratorResponse",
    "LLMConfigRequest",
    "LLMProvider",
    "LLMProviderStatus",
    "PipelineRequest",
    "TestgenRequest",
    # OmniCore
    "CircuitBreakerResetRequest",
    "CircuitBreakerStatus",
    "DatabaseExportRequest",
    "DatabaseQueryRequest",
    "DeadLetterQueueQuery",
    "MessageBusPublishRequest",
    "MessageBusSubscribeRequest",
    "MessageBusTopics",
    "MessageRetryRequest",
    "PluginInfo",
    "PluginInstallRequest",
    "PluginMarketplaceQuery",
    "PluginReloadRequest",
    "RateLimitConfigRequest",
    # SFE
    "ArbiterCommand",
    "ArbiterControlRequest",
    "ArbiterStatus",
    "ArenaCompetitionRequest",
    "ArenaResult",
    "BugAnalysisRequest",
    "BugDetectionRequest",
    "BugPrioritizationRequest",
    "BugReport",
    "CodebaseAnalysisReport",
    "CodebaseAnalysisRequest",
    "ComplianceCheckRequest",
    "DLTAuditQuery",
    "ImportFixRequest",
    "KnowledgeGraphQuery",
    "KnowledgeGraphUpdate",
    "RLEnvironmentStatus",
    "SandboxExecutionRequest",
    "SIEMConfigRequest",
]
