# Copyright © 2025 Novatrax Labs LLC. All Rights Reserved.

"""
Regression Tests for Pipeline Job Run Fixes

This test suite verifies the critical fixes implemented to resolve pipeline
job run failures that were causing incomplete scaffolds and false successes.

Issues Fixed:
1. Empty requirements.txt causing validation failures
2. Main.py validation handling app/ directory layout
3. File discovery using recursive search (rglob)
4. Job completion semantics (only after validation)
5. Packaging excluding nested ZIP files

Test Coverage:
- Requirements.txt fallback generation
- App layout validation logic
- Recursive file discovery for testgen
- Job status transitions and validation gating
- ZIP file exclusion in packaging

Industry Standards:
- ISO 25010: Software Quality Model (Functional Correctness)
- IEEE 829: Software Test Documentation
- OWASP Testing Guide: Security validation testing
"""

import asyncio
import shutil
import tempfile
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from generator.runner.runner_file_utils import (
    materialize_file_map,
    validate_generated_project,
    write_validation_error,
)
from server.schemas import JobStatus, JobStage
from server.services.job_finalization import finalize_job_success, reset_finalization_state
from server.storage import jobs_db
from server.schemas import Job
from datetime import datetime, timezone


class TestRequirementsFallback:
    """Test requirements.txt fallback generation."""

    @pytest.mark.asyncio
    async def test_fallback_triggered_when_missing(self, tmp_path):
        """Test that fallback requirements.txt is generated when file is missing."""
        # Arrange
        output_dir = tmp_path / "generated"
        output_dir.mkdir()

        # Verify requirements.txt does not exist
        requirements_path = output_dir / "requirements.txt"
        assert not requirements_path.exists()

        # Act - Simulate the fallback logic from omnicore_service.py:2742-2767
        if not requirements_path.exists() or requirements_path.stat().st_size == 0:
            fallback_requirements = (
                "# Auto-generated fallback requirements\n"
                "# Generated by pipeline when requirements.txt was missing or empty\n"
                "fastapi>=0.104.0\n"
                "uvicorn[standard]>=0.24.0\n"
                "pydantic>=2.5.0\n"
                "pytest>=7.4.0\n"
                "httpx>=0.25.0\n"
            )
            requirements_path.write_text(fallback_requirements, encoding="utf-8")

        # Assert
        assert requirements_path.exists()
        assert requirements_path.stat().st_size > 0
        content = requirements_path.read_text(encoding="utf-8")
        assert "fastapi>=0.104.0" in content
        assert "uvicorn[standard]>=0.24.0" in content
        assert "pydantic>=2.5.0" in content
        assert "pytest>=7.4.0" in content
        assert "httpx>=0.25.0" in content

    @pytest.mark.asyncio
    async def test_fallback_triggered_when_empty(self, tmp_path):
        """Test that fallback requirements.txt is generated when file is empty."""
        # Arrange
        output_dir = tmp_path / "generated"
        output_dir.mkdir()
        requirements_path = output_dir / "requirements.txt"

        # Create empty requirements.txt
        requirements_path.write_text("", encoding="utf-8")
        assert requirements_path.stat().st_size == 0

        # Act - Simulate the fallback logic
        if not requirements_path.exists() or requirements_path.stat().st_size == 0:
            fallback_requirements = (
                "# Auto-generated fallback requirements\n"
                "# Generated by pipeline when requirements.txt was missing or empty\n"
                "fastapi>=0.104.0\n"
                "uvicorn[standard]>=0.24.0\n"
                "pydantic>=2.5.0\n"
                "pytest>=7.4.0\n"
                "httpx>=0.25.0\n"
            )
            requirements_path.write_text(fallback_requirements, encoding="utf-8")

        # Assert
        assert requirements_path.stat().st_size > 0
        content = requirements_path.read_text(encoding="utf-8")
        assert "fastapi" in content.lower()
        assert "uvicorn" in content.lower()

    @pytest.mark.asyncio
    async def test_fallback_not_triggered_when_valid(self, tmp_path):
        """Test that fallback does not overwrite existing valid requirements.txt."""
        # Arrange
        output_dir = tmp_path / "generated"
        output_dir.mkdir()
        requirements_path = output_dir / "requirements.txt"

        original_content = "django==4.2.0\ncelery==5.3.0\n"
        requirements_path.write_text(original_content, encoding="utf-8")

        # Act - Simulate the fallback logic (should NOT trigger)
        if not requirements_path.exists() or requirements_path.stat().st_size == 0:
            # This block should NOT execute
            pytest.fail("Fallback should not trigger for valid requirements.txt")

        # Assert - original content preserved
        assert requirements_path.read_text(encoding="utf-8") == original_content


class TestAppLayoutValidation:
    """Test validation logic for app/ directory layout."""

    @pytest.mark.asyncio
    async def test_app_layout_detected_and_validated(self, tmp_path):
        """Test that validation correctly handles app/main.py layout."""
        # Arrange - Create app/ layout
        output_dir = tmp_path / "generated"
        app_dir = output_dir / "app"
        app_dir.mkdir(parents=True)

        # Create app/main.py
        main_file = app_dir / "main.py"
        main_file.write_text(
            "from fastapi import FastAPI\napp = FastAPI()\n",
            encoding="utf-8"
        )

        # Create requirements.txt
        req_file = output_dir / "requirements.txt"
        req_file.write_text("fastapi>=0.104.0\n", encoding="utf-8")

        # Act - Run validation
        result = await validate_generated_project(
            output_dir=output_dir,
            required_files=None,  # Will default to ["main.py"]
            check_python_syntax=True,
        )

        # Assert - Validation should pass with app/main.py
        assert result["valid"], f"Validation failed: {result.get('errors', [])}"
        assert result["python_files_valid"] == 1
        assert result["python_files_invalid"] == 0

    @pytest.mark.asyncio
    async def test_root_main_py_validated(self, tmp_path):
        """Test that validation correctly handles root main.py layout."""
        # Arrange - Create root layout
        output_dir = tmp_path / "generated"
        output_dir.mkdir(parents=True)

        # Create main.py at root
        main_file = output_dir / "main.py"
        main_file.write_text(
            "from fastapi import FastAPI\napp = FastAPI()\n",
            encoding="utf-8"
        )

        # Create requirements.txt
        req_file = output_dir / "requirements.txt"
        req_file.write_text("fastapi>=0.104.0\n", encoding="utf-8")

        # Act - Run validation
        result = await validate_generated_project(
            output_dir=output_dir,
            required_files=["main.py"],
            check_python_syntax=True,
        )

        # Assert - Validation should pass with root main.py
        assert result["valid"], f"Validation failed: {result.get('errors', [])}"
        assert result["python_files_valid"] == 1

    @pytest.mark.asyncio
    async def test_nested_main_py_discovered(self, tmp_path):
        """Test that validation finds main.py in non-standard nested locations."""
        # Arrange - Create nested layout (not 'app')
        output_dir = tmp_path / "generated"
        src_dir = output_dir / "src" / "backend"
        src_dir.mkdir(parents=True)

        # Create src/backend/main.py
        main_file = src_dir / "main.py"
        main_file.write_text(
            "from fastapi import FastAPI\napp = FastAPI()\n",
            encoding="utf-8"
        )

        # Create requirements.txt
        req_file = output_dir / "requirements.txt"
        req_file.write_text("fastapi>=0.104.0\n", encoding="utf-8")

        # Act - Run validation
        result = await validate_generated_project(
            output_dir=output_dir,
            required_files=None,  # Validator should find main.py recursively
            check_python_syntax=True,
        )

        # Assert - Validation should pass by finding nested main.py
        # Note: The validator should adjust requirements based on discovered location
        assert result["python_files_valid"] >= 1


class TestFileDiscovery:
    """Test recursive file discovery for testgen."""

    def test_rglob_finds_nested_python_files(self, tmp_path):
        """Test that rglob correctly finds Python files in nested directories."""
        # Arrange - Create nested structure
        output_dir = tmp_path / "generated"
        app_dir = output_dir / "app"
        routes_dir = app_dir / "routes"
        tests_dir = output_dir / "tests"

        for d in [app_dir, routes_dir, tests_dir]:
            d.mkdir(parents=True)

        # Create Python files
        (app_dir / "main.py").write_text("# main\n")
        (app_dir / "__init__.py").write_text("")
        (routes_dir / "api.py").write_text("# api\n")
        (routes_dir / "health.py").write_text("# health\n")
        (tests_dir / "test_main.py").write_text("# test\n")

        # Act - Simulate file discovery like omnicore_service.py:2874-2877
        source_files = [
            f for f in output_dir.rglob("*.py")
            if not f.name.startswith("test_")
        ]

        # Assert - Should find all non-test Python files
        assert len(source_files) == 4  # main.py, __init__.py, api.py, health.py
        file_names = {f.name for f in source_files}
        assert "main.py" in file_names
        assert "api.py" in file_names
        assert "health.py" in file_names
        assert "__init__.py" in file_names
        assert "test_main.py" not in file_names

    def test_glob_fails_to_find_nested_files(self, tmp_path):
        """Test that non-recursive glob would miss nested files (demonstrating the bug)."""
        # Arrange - Create nested structure
        output_dir = tmp_path / "generated"
        app_dir = output_dir / "app"
        app_dir.mkdir(parents=True)

        # Create files at different levels
        (output_dir / "main.py").write_text("# root main\n")
        (app_dir / "routes.py").write_text("# app routes\n")

        # Act - Use non-recursive glob (the old buggy behavior)
        root_files = list(output_dir.glob("*.py"))

        # Assert - glob only finds root level files
        assert len(root_files) == 1
        assert root_files[0].name == "main.py"
        # Demonstrates that glob misses app/routes.py


class TestJobCompletionSemantics:
    """Test job status transitions and validation gating."""

    @pytest.mark.asyncio
    async def test_job_only_completed_after_finalization(self):
        """Test that job status is only set to COMPLETED by finalization service."""
        # Arrange
        job_id = "test-job-123"
        job = Job(
            id=job_id,
            status=JobStatus.RUNNING,
            current_stage=JobStage.GENERATOR_GENERATION,
            input_files=[],
            output_files=[],
            created_at=datetime.now(timezone.utc),
            updated_at=datetime.now(timezone.utc),
            metadata={},
        )
        jobs_db[job_id] = job
        reset_finalization_state()  # Clear finalization tracking

        # Act - Finalize the job
        result_dict = {
            "status": "completed",
            "output_path": "/tmp/test/output",
            "stages_completed": ["codegen", "validate"],
        }
        success = await finalize_job_success(job_id, result_dict)

        # Assert
        assert success
        assert job.status == JobStatus.COMPLETED
        assert job.current_stage == JobStage.COMPLETED
        assert job.completed_at is not None

        # Cleanup
        if job_id in jobs_db:
            del jobs_db[job_id]

    @pytest.mark.asyncio
    async def test_validation_errors_prevent_completion(self, tmp_path):
        """Test that validation errors prevent job from being marked as COMPLETED."""
        # Arrange - Create output with missing required file
        output_dir = tmp_path / "generated"
        output_dir.mkdir()

        # Only create requirements.txt, missing main.py
        req_file = output_dir / "requirements.txt"
        req_file.write_text("fastapi>=0.104.0\n", encoding="utf-8")

        # Act - Run validation
        result = await validate_generated_project(
            output_dir=output_dir,
            required_files=["main.py"],
            check_python_syntax=True,
        )

        # Assert - Validation should fail
        assert not result["valid"]
        assert len(result["errors"]) > 0
        assert any("main.py" in error.lower() for error in result["errors"])


class TestZIPExclusion:
    """Test that output ZIP files are excluded from packaging."""

    @pytest.mark.asyncio
    async def test_output_zip_excluded_from_artifact_collection(self, tmp_path):
        """Test that _output.zip files are excluded from artifact collection."""
        # Arrange - Create directory with files including an _output.zip
        output_dir = tmp_path / "generated"
        output_dir.mkdir()

        # Create regular files
        (output_dir / "main.py").write_text("# main\n")
        (output_dir / "requirements.txt").write_text("fastapi\n")

        # Create nested directory with more files
        app_dir = output_dir / "app"
        app_dir.mkdir()
        (app_dir / "routes.py").write_text("# routes\n")

        # Create an existing _output.zip (should be excluded)
        existing_zip = output_dir / "job123_output.zip"
        existing_zip.write_text("fake zip content\n")

        # Act - Collect artifacts (simulating omnicore_service.py:3036-3037)
        artifacts = list(output_dir.rglob('*'))
        artifact_files = [
            f for f in artifacts
            if f.is_file() and not f.name.endswith('_output.zip')
        ]

        # Assert - _output.zip should be excluded
        file_names = {f.name for f in artifact_files}
        assert "main.py" in file_names
        assert "requirements.txt" in file_names
        assert "routes.py" in file_names
        assert "job123_output.zip" not in file_names

        # Verify total count
        assert len(artifact_files) == 3  # main.py, requirements.txt, routes.py

    def test_download_endpoint_excludes_output_zips(self, tmp_path):
        """Test that download endpoint logic excludes _output.zip files."""
        # Arrange
        job_dir = tmp_path / "job456"
        job_dir.mkdir()

        # Create files
        (job_dir / "main.py").write_text("# main\n")
        (job_dir / "existing_output.zip").write_text("old zip\n")

        # Act - Simulate download logic (jobs.py:478-481)
        files_to_zip = []
        for file_path in job_dir.rglob('*'):
            if file_path.is_file() and not file_path.name.endswith('_output.zip'):
                files_to_zip.append(file_path)

        # Assert
        assert len(files_to_zip) == 1
        assert files_to_zip[0].name == "main.py"


class TestValidationErrorReporting:
    """Test validation error reporting and error.txt generation."""

    @pytest.mark.asyncio
    async def test_write_validation_error_creates_file(self, tmp_path):
        """Test that write_validation_error creates a properly formatted error.txt."""
        # Arrange
        output_dir = tmp_path / "generated"
        output_dir.mkdir()

        validation_result = {
            "valid": False,
            "errors": [
                "Required file missing: main.py",
                "Required file is empty: requirements.txt"
            ],
            "warnings": [
                "No tests/ directory found",
                "requirements.txt does not contain 'pytest'"
            ],
            "file_count": 5,
            "python_files_valid": 3,
            "python_files_invalid": 1,
        }

        # Act
        error_path = await write_validation_error(output_dir, validation_result)

        # Assert
        assert error_path.exists()
        assert error_path.name == "error.txt"
        content = error_path.read_text(encoding="utf-8")

        # Check error content
        assert "VALIDATION FAILED" in content
        assert "Required file missing: main.py" in content
        assert "Required file is empty: requirements.txt" in content
        assert "No tests/ directory found" in content
        assert "Files found: 5" in content


# Integration test combining multiple fixes
class TestPipelineIntegration:
    """Integration tests combining multiple pipeline fixes."""

    @pytest.mark.asyncio
    async def test_full_pipeline_with_app_layout(self, tmp_path):
        """Test complete pipeline flow with app/ layout and requirements fallback."""
        # Arrange - Create app/ layout WITHOUT requirements.txt
        output_dir = tmp_path / "generated"
        app_dir = output_dir / "app"
        tests_dir = output_dir / "tests"

        for d in [app_dir, tests_dir]:
            d.mkdir(parents=True)

        # Create app structure
        (app_dir / "main.py").write_text(
            "from fastapi import FastAPI\napp = FastAPI()\n",
            encoding="utf-8"
        )
        (app_dir / "routes.py").write_text(
            "# routes\n",
            encoding="utf-8"
        )
        (tests_dir / "test_main.py").write_text(
            "def test_app(): assert True\n",
            encoding="utf-8"
        )

        # Act 1 - Simulate requirements fallback
        requirements_path = output_dir / "requirements.txt"
        if not requirements_path.exists() or requirements_path.stat().st_size == 0:
            fallback_requirements = (
                "fastapi>=0.104.0\n"
                "uvicorn[standard]>=0.24.0\n"
                "pydantic>=2.5.0\n"
                "pytest>=7.4.0\n"
                "httpx>=0.25.0\n"
            )
            requirements_path.write_text(fallback_requirements, encoding="utf-8")

        # Act 2 - Run validation
        validation_result = await validate_generated_project(
            output_dir=output_dir,
            required_files=None,  # Let validator detect app/ layout
            check_python_syntax=True,
        )

        # Act 3 - Discover source files for testgen
        source_files = [
            f for f in output_dir.rglob("*.py")
            if not f.name.startswith("test_")
        ]

        # Assert - All steps should succeed
        assert requirements_path.exists()
        assert "fastapi" in requirements_path.read_text().lower()

        assert validation_result["valid"], f"Errors: {validation_result.get('errors')}"
        assert validation_result["python_files_valid"] >= 2  # main.py + routes.py

        assert len(source_files) >= 2  # Should find app/main.py and app/routes.py
        source_names = {f.name for f in source_files}
        assert "main.py" in source_names
        assert "routes.py" in source_names


# Run tests with pytest
if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
