# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audit_log.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0f\x61udit_log.proto\x12\taudit_log"\xe5\x02\n\x10LogActionRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65tails_json\x18\x02 \x01(\t\x12\x1b\n\x0erequirement_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nsession_id\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x15\n\x08trace_id\x18\x05 \x01(\tH\x02\x88\x01\x01\x12\x14\n\x07span_id\x18\x06 \x01(\tH\x03\x88\x01\x01\x12\x12\n\x05\x61\x63tor\x18\x07 \x01(\tH\x04\x88\x01\x01\x12\x17\n\nip_address\x18\x08 \x01(\tH\x05\x88\x01\x01\x12\x18\n\x0bgeolocation\x18\t \x01(\tH\x06\x88\x01\x01\x12\x17\n\x0f\x63ompliance_tags\x18\n \x03(\tB\x11\n\x0f_requirement_idB\r\n\x0b_session_idB\x0b\n\t_trace_idB\n\n\x08_span_idB\x08\n\x06_actorB\r\n\x0b_ip_addressB\x0e\n\x0c_geolocationJ\x04\x08\x0b\x10\x15"W\n\x11LogActionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1a\n\rerror_message\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_error_messageJ\x04\x08\x03\x10\x0b\x32\xa4\x01\n\x0c\x41uditService\x12H\n\tLogAction\x12\x1b.audit_log.LogActionRequest\x1a\x1c.audit_log.LogActionResponse"\x00\x12J\n\tLogStream\x12\x1b.audit_log.LogActionRequest\x1a\x1c.audit_log.LogActionResponse"\x00(\x01\x42 \n\x0e\x61i.x.audit_logZ\x0ex.ai/audit_logb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "audit_log_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n\016ai.x.audit_logZ\016x.ai/audit_log"
    )
    _globals["_LOGACTIONREQUEST"]._serialized_start = 31
    _globals["_LOGACTIONREQUEST"]._serialized_end = 388
    _globals["_LOGACTIONRESPONSE"]._serialized_start = 390
    _globals["_LOGACTIONRESPONSE"]._serialized_end = 477
    _globals["_AUDITSERVICE"]._serialized_start = 480
    _globals["_AUDITSERVICE"]._serialized_end = 644
# @@protoc_insertion_point(module_scope)
