# Copyright © 2025 Novatrax Labs LLC. All Rights Reserved.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from . import audit_log_pb2 as audit__log__pb2

GRPC_GENERATED_VERSION = "1.63.2"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.65.0"
SCHEDULED_RELEASE_DATE = "June 25, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in audit_log_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class AuditServiceStub(object):
    """The AuditService provides methods for logging actions to a secure,
    tamper-evident audit trail. It supports both single-entry and streaming ingestion.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogAction = channel.unary_unary(
            "/audit_log.AuditService/LogAction",
            request_serializer=audit__log__pb2.LogActionRequest.SerializeToString,
            response_deserializer=audit__log__pb2.LogActionResponse.FromString,
            _registered_method=True,
        )
        self.LogStream = channel.stream_unary(
            "/audit_log.AuditService/LogStream",
            request_serializer=audit__log__pb2.LogActionRequest.SerializeToString,
            response_deserializer=audit__log__pb2.LogActionResponse.FromString,
            _registered_method=True,
        )


class AuditServiceServicer(object):
    """The AuditService provides methods for logging actions to a secure,
    tamper-evident audit trail. It supports both single-entry and streaming ingestion.
    """

    def LogAction(self, request, context):
        """Logs a single action. This is a unary RPC for individual, transactional events."""
        import hashlib
        import json

        # Build entry data for hash chain
        entry_data = json.dumps(
            {
                "action": request.action,
                "details_json": request.details_json,
                "actor": request.actor if request.HasField("actor") else None,
                "session_id": request.session_id if request.HasField("session_id") else None,
            },
            sort_keys=True,
        )
        entry_hash = hashlib.sha256(entry_data.encode()).hexdigest()

        # Attempt to write to the audit log backend (non-blocking best-effort)
        try:
            import asyncio
            from generator.audit_log.audit_log import log_action as _log_action

            details = {}
            if request.details_json:
                try:
                    details = json.loads(request.details_json)
                except json.JSONDecodeError:
                    details = {"raw": request.details_json}
            details["_entry_hash"] = entry_hash

            try:
                asyncio.get_running_loop()
                asyncio.ensure_future(
                    _log_action(action=request.action, details=details)
                )
            except RuntimeError:
                asyncio.run(
                    _log_action(action=request.action, details=details)
                )
        except Exception:
            pass  # Non-blocking — log locally on failure

        return audit__log__pb2.LogActionResponse(status="success")

    def LogStream(self, request_iterator, context):
        """Logs a stream of actions for high-throughput, bulk data processing
        or continuous event streaming from another service.
        """
        import hashlib
        import json

        count = 0
        last_hash = "genesis"

        for request in request_iterator:
            # Build chained hash entry
            entry_data = json.dumps(
                {
                    "prev_hash": last_hash,
                    "action": request.action,
                    "details_json": request.details_json,
                    "actor": request.actor if request.HasField("actor") else None,
                },
                sort_keys=True,
            )
            last_hash = hashlib.sha256(entry_data.encode()).hexdigest()
            count += 1

            # Attempt to write to the audit log backend (best-effort)
            try:
                import asyncio
                from generator.audit_log.audit_log import log_action as _log_action

                details = {}
                if request.details_json:
                    try:
                        details = json.loads(request.details_json)
                    except json.JSONDecodeError:
                        details = {"raw": request.details_json}
                details["_entry_hash"] = last_hash
                details["_stream_index"] = count

                try:
                    asyncio.get_running_loop()
                    asyncio.ensure_future(
                        _log_action(action=request.action, details=details)
                    )
                except RuntimeError:
                    asyncio.run(
                        _log_action(action=request.action, details=details)
                    )
            except Exception:
                pass  # Non-blocking — continue stream processing on error

        return audit__log__pb2.LogActionResponse(
            status="success" if count > 0 else "partial_success"
        )


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "LogAction": grpc.unary_unary_rpc_method_handler(
            servicer.LogAction,
            request_deserializer=audit__log__pb2.LogActionRequest.FromString,
            response_serializer=audit__log__pb2.LogActionResponse.SerializeToString,
        ),
        "LogStream": grpc.stream_unary_rpc_method_handler(
            servicer.LogStream,
            request_deserializer=audit__log__pb2.LogActionRequest.FromString,
            response_serializer=audit__log__pb2.LogActionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "audit_log.AuditService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AuditService(object):
    """The AuditService provides methods for logging actions to a secure,
    tamper-evident audit trail. It supports both single-entry and streaming ingestion.
    """

    @staticmethod
    def LogAction(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/audit_log.AuditService/LogAction",
            audit__log__pb2.LogActionRequest.SerializeToString,
            audit__log__pb2.LogActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LogStream(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/audit_log.AuditService/LogStream",
            audit__log__pb2.LogActionRequest.SerializeToString,
            audit__log__pb2.LogActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
