"""String template constants used by fallback generators.

Separated from ``fallback_generators.py`` to keep that module under the
250-line limit.  These are inert string constants with no logic.
"""

from __future__ import annotations

JINJA2_README_TEMPLATE = """# {{ project_name }}

A {{ language }} application generated by The Code Factory.

## Description

This project was automatically generated and includes a complete application structure with:
- RESTful API endpoints{% if endpoints %}
- {{ endpoints|length }} defined routes{% endif %}
- Dependency management
- Testing infrastructure
- Deployment configuration (Docker, Kubernetes, Helm)

## Installation

1. Clone the repository or extract the generated archive

2. Install dependencies:
```bash
pip install -r requirements.txt
```

{% if dependencies %}
### Dependencies

The project includes the following key dependencies:
{% for dep in dependencies %}
- {{ dep }}
{% endfor %}
{% endif %}

## Running the Application

Start the development server:

```bash
uvicorn main:app --host 0.0.0.0 --port 8000
```

Or if using the app/ structure:

```bash
uvicorn app.main:app --host 0.0.0.0 --port 8000
```

The API will be available at: `http://localhost:8000`

### Health Check

Test the health check endpoint:

```bash
curl http://localhost:8000/health
```

Expected response:
```json
{"status": "healthy"}
```

{% if endpoints %}
## API Endpoints

The following endpoints are available:

{% for endpoint in endpoints %}
- {{ endpoint }}
{% endfor %}

For complete API documentation, visit: `http://localhost:8000/docs`
{% endif %}

## Testing

Run the test suite:

```bash
pytest
```

Run with coverage:

```bash
pytest --cov=. --cov-report=html
```

## Deployment

### Docker

Build the Docker image:

```bash
docker build -t {{ project_name }}:latest .
```

Run the container:

```bash
docker run -p 8000:8000 {{ project_name }}:latest
```

### Kubernetes

Deploy to Kubernetes:

```bash
kubectl apply -f k8s/
```

### Helm

Install using Helm:

```bash
helm install {{ project_name }} ./helm
```

## Project Structure

{% if file_list %}
Key files:
{% for file in file_list %}
- {{ file }}
{% endfor %}
{% endif %}

## License

See LICENSE file for details.

## Support

For issues or questions, please refer to the project documentation or contact the development team.
"""

PLAIN_README_TEMPLATE = """# {project_name}

A {language} application generated by The Code Factory.

## Description

This project was automatically generated and includes a complete application structure with:
- RESTful API endpoints
- Dependency management
- Testing infrastructure
- Deployment configuration (Docker, Kubernetes, Helm)

## Installation

1. Clone the repository or extract the generated archive

2. Install dependencies:
```bash
pip install -r requirements.txt
```

## Running the Application

Start the development server:

```bash
uvicorn main:app --host 0.0.0.0 --port 8000
```

Or if using the app/ structure:

```bash
uvicorn app.main:app --host 0.0.0.0 --port 8000
```

The API will be available at: `http://localhost:8000`

### Health Check

Test the health check endpoint:

```bash
curl http://localhost:8000/health
```

Expected response:
```json
{{"status": "healthy"}}
```

## API Endpoints

For complete API documentation, visit: `http://localhost:8000/docs`

## Testing

Run the test suite:

```bash
pytest
```

Run with coverage:

```bash
pytest --cov=. --cov-report=html
```

## Deployment

### Docker

Build the Docker image:

```bash
docker build -t {project_name}:latest .
```

Run the container:

```bash
docker run -p 8000:8000 {project_name}:latest
```

### Kubernetes

Deploy to Kubernetes:

```bash
kubectl apply -f k8s/
```

### Helm

Install using Helm:

```bash
helm install {project_name} ./helm
```

## License

See LICENSE file for details.

## Support

For issues or questions, please refer to the project documentation or contact the development team.
"""

STYLE_CSS_TEMPLATE = '''/* Generated CSS for the application */
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
}

main {
    flex: 1;
}

.navbar-brand {
    font-weight: bold;
}

#app-content {
    padding: 20px 0;
}

/* Responsive adjustments */
@media (max-width: 768px) {
    .container {
        padding: 0 15px;
    }
}'''

APP_JS_TEMPLATE = '''// Generated JavaScript for the application
document.addEventListener("DOMContentLoaded", function() {
    console.log("Application initialized");

    // API base URL - adjust based on your backend
    const API_BASE = window.location.origin;

    // Example: Load data from API
    async function loadData() {
        try {
            const response = await fetch(`${API_BASE}/api/health`);
            if (response.ok) {
                const data = await response.json();
                console.log("API health check:", data);
            }
        } catch (error) {
            console.log("API not available or running on different port");
        }
    }

    loadData();
});'''
