# Copyright © 2025 Novatrax Labs LLC. All Rights Reserved.

# -*- coding: utf-8 -*-
"""
Production-Ready Code Generation Post-Processor

This module parses, validates, annotates, and scans code generated by an LLM.

Capabilities:
- Multi-file JSON response parsing with single-file fallback.
- Robust code extraction from various LLM response formats (markdown fences, conversational text).
- Language-aware syntax validation (Python, JS/TS, Java, Go) using native tools.
- Secret scanning via heuristics.
- Unified SAST integration via `scan_for_vulnerabilities` from runner utilities.
- Requirements-to-code traceability annotations.
- Safe degradation when external tools or runner utilities are unavailable.

Code Extraction Features (Enhanced):
- Multi-strategy extraction: language-specific fences, generic fences, preamble detection
- Handles conversational preamble ("Here's the code:") and postamble text
- Extracts largest code block when multiple blocks are present
- Supports Python decorators, imports, class/function definitions as code markers
- Case-insensitive fence matching (```python, ```PYTHON, ```py)
- Comprehensive logging for debugging extraction issues

Security Note:
- Set SECURITY_SCANNER_STRICT_MODE=1 in production to enforce security scanner availability.
- When the scanner is unavailable, results will clearly indicate scanning was NOT performed.

Version: 2.0 (Enhanced code extraction with industry-standard robustness)
"""

from __future__ import annotations

import json
import logging
import os
import re
import subprocess
import sys
import tempfile
from functools import lru_cache
from typing import Any, Dict, List, Tuple, Union

from .syntax_auto_repair import SyntaxAutoRepair

logger = logging.getLogger(__name__)

# ==============================================================================
# --- Runner / Environment Integration ---
# ==============================================================================

# Environment variable to control security scanner behavior
# SECURITY_SCANNER_STRICT_MODE=1: Raise error if scanner unavailable (production)
# SECURITY_SCANNER_STRICT_MODE=0: Allow fallback behavior (development/testing)
import inspect

_SECURITY_SCANNER_STRICT_MODE = os.getenv("SECURITY_SCANNER_STRICT_MODE", "0") == "1"
_TESTING_MODE = os.getenv("TESTING") == "1" or "pytest" in sys.modules

# Track whether we're using real or stub implementations
_USING_STUB_AUDIT_LOG = False
_USING_STUB_SECURITY_SCANNER = False


class SecurityScannerUnavailableError(Exception):
    """Raised when the security scanner is required but not available.

    This error indicates that security scanning cannot be performed,
    which is a critical security gap in production environments.
    """

    pass


# Counter for tracking audit logging failures (for compliance monitoring)
_AUDIT_LOG_FAILURE_COUNT = 0


try:  # Prefer real runner logging if available
    # --- FIX: Changed import to be relative and import sync version ---
    from ...runner.runner_audit import log_audit_event_sync as _runner_log_audit_event
except ImportError:  # Fallback stub
    _USING_STUB_AUDIT_LOG = True

    def _runner_log_audit_event(
        event_type: str, payload: Dict[str, Any] | None = None
    ) -> None:
        global _AUDIT_LOG_FAILURE_COUNT
        _AUDIT_LOG_FAILURE_COUNT += 1

        # Log at ERROR level - audit trail loss is a serious compliance concern
        logger.error(
            "AUDIT LOG UNAVAILABLE [COMPLIANCE RISK]: Audit event NOT recorded. "
            "This is a compliance violation in production. "
            "event_type=%s, failure_count=%d",
            event_type,
            _AUDIT_LOG_FAILURE_COUNT,
        )


try:  # Prefer real security utilities if available
    # --- FIX: Changed import to be relative ---
    from ...runner.runner_security_utils import (
        scan_for_vulnerabilities as _runner_scan_for_vulnerabilities,
    )
except ImportError:  # Fallback stub
    _USING_STUB_SECURITY_SCANNER = True

    def _runner_scan_for_vulnerabilities(code_files: Dict[str, str]) -> Dict[str, Any]:
        """Stub implementation that raises an error or returns a warning marker.

        SECURITY CRITICAL: This stub does NOT perform actual security scanning.
        In production environments, this is a serious security gap.
        """
        # Log at ERROR level, not just warning - this is a security issue
        logger.error(
            "SECURITY SCANNER UNAVAILABLE: scan_for_vulnerabilities is using a stub "
            "implementation. NO ACTUAL SECURITY SCANNING IS BEING PERFORMED. "
            "This is a CRITICAL SECURITY GAP in production environments."
        )

        # Return a result that clearly indicates scanning was NOT performed
        return {
            "_scanner_status": {
                "scanned": False,
                "reason": "Security scanner unavailable - stub implementation in use",
                "security_gap": True,
                "recommendation": "Install runner security utilities or set SECURITY_SCANNER_STRICT_MODE=1 to fail on unavailable scanner",
            }
        }


def log_audit_event(event_type: str, payload: Dict[str, Any] | None = None) -> None:
    """
    Direct wrapper for audit logging in synchronous contexts.
    
    Uses log_audit_event_sync from runner_audit which handles async via create_task.
    """
    payload = payload or {}
    fn = _runner_log_audit_event
    try:
        # _runner_log_audit_event is now the sync version, just call it directly
        fn(event_type, payload)
    except Exception:  # pragma: no cover - logging failures must never break main flow
        logger.exception("Failed to emit audit event: %s", event_type)


def log_action(event_type: str, payload: Dict[str, Any] | None = None) -> None:
    """
    Alias used throughout this module and by tests.
    """
    log_audit_event(event_type, payload)


def scan_for_vulnerabilities(code_files: Dict[str, str]) -> Dict[str, Any]:
    """
    Wrapper for runner-based SAST (Static Application Security Testing).

    SECURITY CRITICAL: This function performs security scanning on generated code.
    If the underlying scanner is unavailable:
    - In strict mode (SECURITY_SCANNER_STRICT_MODE=1): Raises SecurityScannerUnavailableError
    - In non-strict mode: Returns a result with a clear warning that scanning was skipped

    Returns a dict structure:
        { filename: { "issues": [ ... ] }, ... }

    In stub mode, returns:
        { "_scanner_status": { "scanned": False, "security_gap": True, ... } }

    Raises:
        SecurityScannerUnavailableError: In strict mode when scanner is unavailable.
    """
    # Check if we're using a stub and strict mode is enabled
    if _USING_STUB_SECURITY_SCANNER and _SECURITY_SCANNER_STRICT_MODE:
        raise SecurityScannerUnavailableError(
            "Security scanner is not available but SECURITY_SCANNER_STRICT_MODE is enabled. "
            "Cannot proceed without security scanning in production mode. "
            "Please install runner security utilities (runner.runner_security_utils) "
            "or disable strict mode for development/testing."
        )

    try:
        result = _runner_scan_for_vulnerabilities(code_files)

        # If using stub, ensure the result clearly indicates scanning wasn't performed
        if _USING_STUB_SECURITY_SCANNER:
            # Log a warning every time the stub is used
            logger.warning(
                "SECURITY WARNING: scan_for_vulnerabilities returned stub result. "
                "No actual security scanning was performed on %d files.",
                len(code_files),
            )

        return result
    except SecurityScannerUnavailableError:
        # Re-raise our custom exception
        raise
    except Exception as e:  # pragma: no cover - defensive
        logger.exception("scan_for_vulnerabilities failed unexpectedly: %s", e)

        # In strict mode, don't silently continue on errors
        if _SECURITY_SCANNER_STRICT_MODE:
            raise SecurityScannerUnavailableError(
                f"Security scanner failed unexpectedly: {e}. "
                f"Cannot proceed without security scanning in strict mode."
            ) from e

        # Return a result indicating failure
        return {
            "_scanner_status": {
                "scanned": False,
                "reason": f"Scanner failed with error: {e}",
                "security_gap": True,
            }
        }


def is_security_scanner_available() -> bool:
    """Check if the real security scanner is available.

    Returns:
        True if the real runner security scanner is available, False if using stub.
    """
    return not _USING_STUB_SECURITY_SCANNER


def get_security_scanner_status() -> Dict[str, Any]:
    """Get the current status of the security scanner.

    Returns a dict with:
        - available: bool
        - strict_mode: bool
        - using_stub: bool
        - recommendation: str (if using stub)
    """
    status = {
        "available": not _USING_STUB_SECURITY_SCANNER,
        "strict_mode": _SECURITY_SCANNER_STRICT_MODE,
        "using_stub": _USING_STUB_SECURITY_SCANNER,
    }

    if _USING_STUB_SECURITY_SCANNER:
        status["recommendation"] = (
            "Install runner security utilities for production use. "
            "Set SECURITY_SCANNER_STRICT_MODE=1 to enforce scanner availability."
        )

    return status


def get_audit_log_failure_count() -> int:
    """Get the count of audit logging failures.

    This is useful for compliance monitoring and alerting.
    A non-zero count indicates audit events have been lost,
    which is a serious compliance concern.

    Returns:
        The number of audit logging failures since module load.
    """
    return _AUDIT_LOG_FAILURE_COUNT


def is_audit_logging_available() -> bool:
    """Check if the real audit logging is available.

    Returns:
        True if real runner audit logging is available, False if using stub.
    """
    return not _USING_STUB_AUDIT_LOG


# ==============================================================================
# --- Constants ---
# ==============================================================================

DEFAULT_FILENAME = "main.py"
ERROR_FILENAME = "error.txt"

# Very lightweight heuristic: any assignment to a suspicious name is flagged.
SECRET_REGEX = re.compile(
    r"(api_key|apikey|secret|token|password)\s*=",
    re.IGNORECASE,
)

# Language-specific comment styles for traceability
COMMENT_STYLES: Dict[str, Tuple[str, str]] = {
    # lang or extension : (start, end)
    "python": ("#", ""),
    "py": ("#", ""),
    "javascript": ("//", ""),
    "js": ("//", ""),
    "typescript": ("//", ""),
    "ts": ("//", ""),
    "java": ("//", ""),
    "csharp": ("//", ""),
    "cs": ("//", ""),
    "go": ("//", ""),
    "rust": ("//", ""),
    "rs": ("//", ""),
    "ruby": ("#", ""),
    "rb": ("#", ""),
    "php": ("//", ""),
    "swift": ("//", ""),
    "kotlin": ("//", ""),
    "kt": ("//", ""),
    "css": ("/*", "*/"),
    "sql": ("--", ""),
}

DEFAULT_COMMENT_STYLE = ("#", "")


# ==============================================================================
# --- Tooling Helpers ---
# ==============================================================================


@lru_cache(maxsize=None)
def _is_tool_available(tool: str) -> bool:
    """
    Checks if an executable is available on PATH. Cached for efficiency.
    """
    from shutil import which

    available = which(tool) is not None
    logger.debug("Tool availability check: %s -> %s", tool, available)
    return available


# ==============================================================================
# --- Core: LLM Response Parsing ---
# ==============================================================================


def parse_llm_response(response: Union[str, Dict[str, Any]], lang: str = "python") -> Dict[str, str]:
    """
    Parses the LLM response, handling both multi-file JSON and single-file code.

    Multi-file mode expects:
        {
          "files": {
            "main.py": "<code>",
            "util.py": "<code>"
          }
        }

    Behavior:
    - For multi-file JSON:
        - Each file is cleaned and syntax-validated.
        - Valid files are returned as-is.
        - Invalid files are summarized into ERROR_FILENAME.
    - For non-JSON:
        - Treat as a single file; validate.
        - Return DEFAULT_FILENAME or ERROR_FILENAME accordingly.
    
    Args:
        response: Either a string (legacy behavior) or a dict (OpenAI API response format)
        lang: Target programming language for syntax validation
    
    Returns:
        Dictionary mapping filenames to code content
    """
    # Handle dict response from OpenAI API
    if isinstance(response, dict):
        # Extract content from OpenAI chat completion response
        raw = ''
        try:
            # Try OpenAI chat completion format first
            if 'choices' in response and response['choices']:
                raw = response['choices'][0].get('message', {}).get('content', '')
        except (KeyError, TypeError):
            # KeyError: unexpected dict structure
            # TypeError: choices is not subscriptable or message is not a dict
            pass
        
        # Fallback: try to get 'content' or 'text' directly if extraction failed
        if not raw:
            raw = response.get('content', response.get('text', ''))
        
        logger.debug("Extracted content from dict response, length: %d", len(raw) if raw else 0)
    else:
        raw = response
    
    raw = raw.strip() if raw else ''
    
    # Log raw response length for debugging
    logger.debug(
        "Processing LLM response - length: %d chars, first 100: %s",
        len(raw),
        raw[:100] if raw else "(empty)"
    )
    
    # For robustness, strip outer code fences before JSON parsing attempt.
    cleaned_for_json = _clean_code_block(raw)
    
    # --- 1. Try multi-file JSON format (only if cleaning produced something) ---
    if cleaned_for_json:
        try:
            payload = json.loads(cleaned_for_json)
            if isinstance(payload, dict) and isinstance(payload.get("files"), dict):
                files_obj = payload["files"]
                code_files: Dict[str, str] = {}
                errors: Dict[str, str] = {}
                repair_logs: List[str] = []

                for filename, content in files_obj.items():
                    if not isinstance(content, str):
                        errors[filename] = "Content is not a string."
                        continue

                    cleaned = _clean_code_block(content)
                    
                    # Use validate_and_repair_syntax instead of _validate_syntax
                    validation_result = validate_and_repair_syntax(cleaned, lang, filename)

                    if validation_result['valid']:
                        code_files[filename] = validation_result['code']
                        
                        # Log if auto-repair was used
                        if validation_result['auto_repaired']:
                            repair_info = f"Auto-repaired {filename}: {', '.join(validation_result['repairs_applied'])}"
                            repair_logs.append(repair_info)
                            logger.info(repair_info)
                    else:
                        logger.warning(
                            "Syntax validation failed for '%s' (%s). Details: %s",
                            filename,
                            lang,
                            validation_result['error'],
                        )
                        errors[filename] = validation_result['error']

                # If any file failed, emit an aggregated error.txt
                if errors:
                    lines = [
                        "One or more files failed syntax validation.",
                        "",
                    ]
                    for fname, emsg in errors.items():
                        lines.append(f"[{fname}]")
                        lines.append(str(emsg))
                        lines.append("")
                    code_files[ERROR_FILENAME] = "\n".join(lines).rstrip()

                if code_files:
                    # Perform production-ready validation
                    is_production_ready, prod_error = validate_production_ready(code_files)
                    if not is_production_ready:
                        logger.warning("Production-ready validation failed for multi-file response")
                        code_files[ERROR_FILENAME] = prod_error
                    
                    log_action(
                        "Parsed Multi-File Response",
                        {
                            "files": [f for f in code_files.keys() if f != ERROR_FILENAME],
                            "language": lang,
                            "had_errors": bool(errors),
                            "production_ready": is_production_ready,
                            "auto_repairs": repair_logs if repair_logs else None,
                        },
                    )
                    return code_files
                # If nothing usable, fall through to single-file handling.

        except json.JSONDecodeError:
            logger.info("LLM response is not valid JSON; using single-file fallback.")
        except Exception as e:
            logger.error("Unexpected error while parsing JSON LLM response: %s", e)

    # --- 2. Single-file fallback ---
    cleaned_code = _clean_code_block(raw)
    
    # If cleaning resulted in empty string but we have raw content,
    # check if it's likely explanatory prose or actual code
    if not cleaned_code and raw:
        # Check if the raw text contains prose indicators (explanatory text)
        raw_lower = raw.lower()
        PROSE_INDICATORS = (
            'i need', 'i apologize', 'i cannot', "i'm sorry", "i can't",
            'please provide', 'could you', 'would you', 'you need to',
            'more information', 'clarify', 'specify', 'details about',
            'unfortunately', 'however', 'before i can', 'in order to',
            'help me understand', 'not enough details', 'provide enough',
        )
        
        # If raw text contains prose indicators, it's explanatory, not code
        if any(indicator in raw_lower for indicator in PROSE_INDICATORS):
            error_msg = (
                "LLM response did not contain recognizable code. "
                "The response appears to be an explanation or clarification request. "
                f"Response preview: {raw[:200]}..."
            )
            logger.error(error_msg)
            return {ERROR_FILENAME: error_msg}
        
        # Otherwise, treat as raw code (legacy behavior for compatibility)
        logger.warning(
            "No code markers found in response after cleaning. "
            "Falling back to using raw response as-is for compatibility. "
            "Preview: %s",
            raw[:150] + "..." if len(raw) > 150 else raw
        )
        log_action(
            "Parsed Single-File Response (Raw Fallback)",
            {"file": DEFAULT_FILENAME, "language": lang, "production_ready": False},
        )
        return {DEFAULT_FILENAME: raw}
    
    # Use validate_and_repair_syntax instead of _validate_syntax
    validation_result = validate_and_repair_syntax(cleaned_code, lang, DEFAULT_FILENAME)

    if validation_result['valid']:
        # Use repaired code if auto-repair was applied
        final_code = validation_result['code']
        
        # Perform production-ready validation for single file
        single_file_dict = {DEFAULT_FILENAME: final_code}
        is_production_ready, prod_error = validate_production_ready(single_file_dict)
        
        if not is_production_ready:
            logger.warning("Production-ready validation failed for single-file response")
            return {
                DEFAULT_FILENAME: final_code,
                ERROR_FILENAME: prod_error
            }
        
        log_action(
            "Parsed Single-File Response",
            {
                "file": DEFAULT_FILENAME, 
                "language": lang, 
                "production_ready": True,
                "auto_repaired": validation_result['auto_repaired'],
                "repairs_applied": validation_result['repairs_applied'] if validation_result['auto_repaired'] else None,
            },
        )
        return {DEFAULT_FILENAME: final_code}

    logger.error(
        "Syntax validation failed for single-file response (%s). Details: %s",
        lang,
        validation_result['error'],
    )
    error_content = (
        f"Generated code failed syntax validation for language '{lang}'.\n\n"
        f"Validation Tool Output:\n{validation_result['error']}"
    )
    return {ERROR_FILENAME: error_content}


# ==============================================================================
# --- Helpers: Cleaning & Syntax Validation ---
# ==============================================================================


def _contains_code_markers(text: str) -> bool:
    """
    Check if text contains indicators that it's actual code rather than prose.
    
    This function helps distinguish between:
    - Actual code (imports, function definitions, class declarations, etc.)
    - Explanatory text from LLM (apologies, clarification requests, questions)
    
    Args:
        text: The text to analyze
        
    Returns:
        True if text appears to be code, False if it's likely prose/explanation
        
    Examples:
        >>> _contains_code_markers("import os\\ndef main(): pass")
        True
        >>> _contains_code_markers("I need more information about your requirements")
        False
        
    Note:
        This is a heuristic check that uses indicator counting. It's designed to
        catch cases where the LLM returns explanatory text instead of code.
    """
    if not text or len(text) < 5:
        return False
    
    # Code indicators (must have at least one)
    CODE_INDICATORS = (
        # Python-specific keywords and constructs
        'import ', 'from ', 'def ', 'class ', 'async def',
        'if __name__', 'return ', 'yield ', 'raise ',
        'for ', 'while ', 'try:', 'except', 'with ',
        'lambda ', 'assert ', 'pass', 'break', 'continue',
        # Function/method calls - common in Python
        'print(', 'len(', 'range(', 'str(', 'int(', 'open(',
        # Common patterns
        '= ', '==', '!=', '()', '[]', '{}',
        # Comments/docstrings
        '#', '"""', "'''",
        # Operators
        '+=', '-=', '*=', '/=', '**', '//',
        # Other languages
        'function ', 'const ', 'let ', 'var ', 'public ', 'private ',
        'package ', 'namespace ', 'using ', 'include ', '#include',
    )
    
    # Prose indicators (if these dominate, it's likely not code)
    # Import shared Presidio placeholders
    try:
        from generator.runner.runner_security_utils import PRESIDIO_PLACEHOLDERS
        presidio_placeholders = PRESIDIO_PLACEHOLDERS
    except ImportError:
        # Fallback if import fails
        presidio_placeholders = ['<ORGANIZATION>', '<URL>', '<PERSON>', '<API_KEY>']
    
    PROSE_INDICATORS = (
        'I need', 'I apologize', 'I cannot', "I'm sorry", "I can't",
        'please provide', 'could you', 'would you', 'you need to',
        'more information', 'clarify', 'specify', 'details about',
        'unfortunately', 'however', 'therefore',
        'before I can', 'in order to', 'help me understand',
        'not enough details', 'provide enough', 'are placeholders',
    ) + tuple(presidio_placeholders)
    
    text_lower = text.lower()
    
    # Count indicators (using lowercase for consistent comparison)
    code_score = sum(1 for indicator in CODE_INDICATORS if indicator.lower() in text_lower)
    prose_score = sum(1 for indicator in PROSE_INDICATORS if indicator.lower() in text_lower)
    
    # If prose dominates, it's not code
    if prose_score > code_score:
        return False
    
    # Must have at least one code indicator
    return code_score > 0


def _clean_code_block(code_content: str) -> str:
    """
    Extracts clean code from LLM responses by removing markdown fences and conversational text.
    
    This function implements a multi-strategy approach to extract code from various LLM response formats:
    1. Language-specific markdown fences (```python, ```py)
    2. Generic markdown fences (```)
    3. Conversational preamble detection and removal
    
    When multiple code blocks are present, the largest block is returned as it's most likely
    to contain the complete implementation rather than a small example.
    
    Args:
        code_content: Raw LLM response text that may contain code mixed with explanatory text
        
    Returns:
        Cleaned code string with markdown fences and preamble removed
        
    Examples:
        >>> _clean_code_block("```python\\ndef hello():\\n    pass\\n```")
        'def hello():\\n    pass'
        
        >>> _clean_code_block("Here's the code:\\n\\nimport os\\n\\ndef main(): pass")
        'import os\\n\\ndef main(): pass'
    
    Note:
        This function is designed to be robust against various LLM response formats
        and will gracefully degrade to returning the input stripped if no patterns match.
    """
    if not code_content:
        logger.warning("_clean_code_block received empty input")
        return ""
    
    text = code_content.strip()
    
    # Strategy 1: Extract from language-specific markdown fences (```python, ```py, etc.)
    # Pattern matches: ```<language>\ncode\n```
    # Supports: python, py, javascript, js, typescript, ts, java, go, rust, cpp, c++, etc.
    code_block_pattern = r'```(?:python|py|javascript|js|typescript|ts|java|go|rust|cpp|c\+\+|c#|csharp|ruby|php|swift|kotlin)\s*\n(.*?)```'
    matches = re.findall(code_block_pattern, text, flags=re.DOTALL | re.IGNORECASE)
    
    if matches:
        # Return the largest code block (most likely to be the actual code)
        largest_match = max(matches, key=len).strip()
        logger.debug(
            "Extracted code from language-specific fence (length: %d chars)",
            len(largest_match)
        )
        return largest_match
    
    # Strategy 2: Extract from generic markdown fences (```)
    # This pattern matches ANY fence without a language specifier or with other languages
    generic_pattern = r'```\s*\n(.*?)```'
    matches = re.findall(generic_pattern, text, flags=re.DOTALL)
    if matches:
        largest_match = max(matches, key=len).strip()
        logger.debug(
            "Extracted code from generic fence (length: %d chars)",
            len(largest_match)
        )
        return largest_match
    
    # Strategy 2.5: Try single-line code fence format (```code```)
    inline_pattern = r'```(.*?)```'
    matches = re.findall(inline_pattern, text, flags=re.DOTALL)
    if matches:
        largest_match = max(matches, key=len).strip()
        # Only use if it looks like code (contains newlines or code indicators)
        if '\n' in largest_match or _contains_code_markers(largest_match):
            logger.debug(
                "Extracted code from inline fence (length: %d chars)",
                len(largest_match)
            )
            return largest_match
    
    # Strategy 3: No code fences found - strip conversational preamble
    # This handles cases where the LLM didn't use markdown but included explanatory text
    lines = text.split('\n')
    code_start_idx = 0
    
    # Conversational markers that indicate non-code preamble
    # These are checked at line start after stripping and must be followed by space or colon
    PREAMBLE_PATTERNS = (
        'here is', 'here\'s', 'this is', 'this will', 
        'the following', 'below is', 'below you',
        'i will', 'i\'ve', 'i have', 'sure', 'certainly',
        'of course', 'absolutely'
    )
    # Code markers that indicate the start of actual code
    CODE_MARKERS = ('import ', 'from ', 'def ', 'class ', '#', '"""', "'''", '@', 'if ', 'for ', 'while ',
                   'function ', 'const ', 'let ', 'var ', 'package ', 'public ', 'private ', 'namespace ')
    
    for i, line in enumerate(lines):
        stripped = line.strip().lower()
        
        # Skip empty lines
        if not stripped:
            continue
            
        # Skip lines that look like conversational preamble (phrase-based, more specific)
        if any(stripped.startswith(pattern) for pattern in PREAMBLE_PATTERNS):
            code_start_idx = i + 1
            continue
            
        # Stop at first line that looks like code
        if stripped.startswith(CODE_MARKERS):
            break
            
        # Check for assignment statements (but not in conversational context)
        if '=' in stripped and not any(stripped.startswith(pattern) for pattern in PREAMBLE_PATTERNS):
            break
    
    result = '\n'.join(lines[code_start_idx:]).strip()
    
    if code_start_idx > 0:
        logger.debug(
            "Stripped %d lines of preamble text (result length: %d chars)",
            code_start_idx,
            len(result)
        )
    
    # ADDED: Check if result contains any code markers
    # This prevents explanatory text from being passed to syntax validation
    if not _contains_code_markers(result):
        logger.warning(
            "No code markers found in LLM response after cleaning. "
            "Response may be explanatory text rather than code. "
            "Preview: %s",
            result[:150] + "..." if len(result) > 150 else result
        )
        # Return empty string to trigger proper error handling downstream
        return ""
    
    return result


# ==============================================================================
# File Type Detection - Industry Standard Configuration
# ==============================================================================

# Module-level constant for language detection (performance optimization)
# Follows GitHub Linguist and VS Code language identifiers
_EXTENSION_TO_LANGUAGE: Dict[str, str] = {
    # Python
    "py": "python",
    "pyw": "python",
    "pyi": "python",
    # JavaScript/TypeScript
    "js": "javascript",
    "mjs": "javascript",
    "cjs": "javascript",
    "jsx": "javascript",
    "ts": "typescript",
    "tsx": "typescript",
    # Java
    "java": "java",
    # Go
    "go": "go",
    # C/C++
    "c": "c",
    "cpp": "c++",
    "cc": "c++",
    "cxx": "c++",
    "h": "c",
    "hpp": "c++",
    # C#
    "cs": "csharp",
    # Ruby
    "rb": "ruby",
    # PHP
    "php": "php",
    # Rust
    "rs": "rust",
    # Swift
    "swift": "swift",
    # Kotlin
    "kt": "kotlin",
    # Shell
    "sh": "shell",
    "bash": "shell",
    # SQL
    "sql": "sql",
    # Documentation/Config files (should not be validated as code)
    "md": "markdown",
    "markdown": "markdown",
    "txt": "text",
    "rst": "restructuredtext",
    "json": "json",
    "yaml": "yaml",
    "yml": "yaml",
    "toml": "toml",
    "xml": "xml",
    "html": "html",
    "css": "css",
}

# Non-code languages that should skip syntax validation (performance: frozenset)
_NON_CODE_LANGUAGES: frozenset = frozenset({
    "markdown", "text", "restructuredtext",
    "json", "yaml", "toml", "xml", "html", "css"
})


@lru_cache(maxsize=256)
def _infer_language_from_filename(filename: str, default_lang: str = "python") -> str:
    """
    Infer the programming language from a filename's extension.
    
    This is used to determine the appropriate syntax validator when the
    language is not explicitly provided or when validating multi-file responses.
    
    Industry Standards:
        - Follows GitHub Linguist language detection
        - Results cached for performance (LRU cache)
        - Thread-safe caching implementation
        - Input validation for security
    
    Args:
        filename: The filename to analyze (can include path)
        default_lang: Default language to return if extension is unknown
        
    Returns:
        Inferred language name (e.g., 'python', 'javascript', 'java')
        
    Raises:
        TypeError: If filename is not a string
        ValueError: If filename is empty
        
    Examples:
        >>> _infer_language_from_filename("main.py")
        'python'
        >>> _infer_language_from_filename("app.js")
        'javascript'
        >>> _infer_language_from_filename("README.md")
        'markdown'
    """
    # Input validation - defensive programming
    if not isinstance(filename, str):
        raise TypeError(f"filename must be a string, got {type(filename).__name__}")
    
    filename = filename.strip()
    if not filename:
        raise ValueError("filename cannot be empty")
    
    # Security: use basename only to avoid path traversal influencing detection
    basename = os.path.basename(filename)
    
    # Extract extension (case-insensitive)
    ext = os.path.splitext(basename)[1].lstrip(".").lower()
    
    # Return detected language or default
    return _EXTENSION_TO_LANGUAGE.get(ext, default_lang)


@lru_cache(maxsize=256)
def _should_skip_syntax_validation(filename: str) -> bool:
    """
    Determine if a file should skip syntax validation.
    
    Documentation files, configuration files, and other non-code files
    should not be validated as source code.
    
    Industry Standards:
        - Distinguishes data/config from executable code
        - O(1) lookup performance using frozenset
        - Results cached for performance
        - Input validation for security
    
    Args:
        filename: The filename to check
        
    Returns:
        True if syntax validation should be skipped
        
    Raises:
        TypeError: If filename is not a string
        ValueError: If filename is empty
        
    Examples:
        >>> _should_skip_syntax_validation("README.md")
        True
        >>> _should_skip_syntax_validation("config.yaml")
        True
        >>> _should_skip_syntax_validation("main.py")
        False
    """
    # Input validation
    if not isinstance(filename, str):
        raise TypeError(f"filename must be a string, got {type(filename).__name__}")
    
    filename = filename.strip()
    if not filename:
        raise ValueError("filename cannot be empty")
    
    # Get inferred language and check against non-code set
    try:
        lang = _infer_language_from_filename(filename, default_lang="")
        return lang in _NON_CODE_LANGUAGES
    except Exception as e:
        # Log error but default to not skipping (validate for safety)
        logger.error(
            "Error determining if validation should be skipped for '%s': %s. Defaulting to validate.",
            filename,
            e,
            exc_info=True
        )
        return False


def _validate_syntax(code: str, lang: str, filename: str) -> Tuple[bool, str]:
    """
    Validates code syntax using language-appropriate mechanisms.
    
    Industry Standards:
        - Input validation and type checking
        - File type detection to skip non-code files
        - Language inference from filename
        - Comprehensive error messages
        - Graceful degradation when tools unavailable
    
    Args:
        code: The code content to validate
        lang: The programming language
        filename: The filename (used for language detection and context)

    Returns:
        Tuple of (is_valid, message):
            - is_valid: True if syntactically valid or validation skipped
            - message: Empty if valid, error description otherwise
            
    Raises:
        TypeError: If inputs are not of expected types
        
    Examples:
        >>> _validate_syntax("def hello(): pass", "python", "main.py")
        (True, "")
        >>> _validate_syntax("# Documentation", "python", "README.md")
        (True, "Skipped validation for markdown file")
    """
    # Input validation - industry standard defensive programming
    if not isinstance(code, str):
        raise TypeError(f"code must be a string, got {type(code).__name__}")
    
    if not isinstance(lang, str):
        raise TypeError(f"lang must be a string, got {type(lang).__name__}")
    
    if not isinstance(filename, str):
        raise TypeError(f"filename must be a string, got {type(filename).__name__}")
    
    # Check if this file should skip validation (e.g., README.md, config files)
    try:
        if _should_skip_syntax_validation(filename):
            detected_type = _infer_language_from_filename(filename, default_lang="unknown")
            logger.debug(
                "Skipping syntax validation for %s (detected as %s file)",
                filename,
                detected_type
            )
            return True, f"Skipped validation for {detected_type} file"
    except (TypeError, ValueError):
        # Re-raise validation errors
        raise
    except Exception as e:
        # Log unexpected errors but continue with validation for safety
        logger.warning(
            "Error checking if validation should be skipped for '%s': %s. Proceeding with validation.",
            filename,
            e
        )
    
    # Infer language from filename if not provided or if it's generic
    try:
        inferred_lang = _infer_language_from_filename(filename, default_lang="python")
        
        # Use inferred language if original lang is empty or generic
        if not lang or lang.lower() in ("", "text", "plain"):
            lang = inferred_lang
            logger.debug(
                "Inferred language '%s' from filename '%s'",
                lang,
                filename
            )
    except Exception as e:
        logger.warning(
            "Could not infer language from filename '%s': %s. Using provided lang '%s'.",
            filename,
            e,
            lang
        )
    
    lang_l = (lang or "").lower()

    # Validate that code is not empty
    if not code.strip():
        logger.warning("Empty code block for %s; treating as error.", filename)
        return False, (
            "Empty code block received - no valid code generated. "
            "This may indicate the LLM returned explanatory text instead of code. "
            "Try providing more specific requirements or examples."
        )

    # --- Python ---
    if lang_l in ("python", "py"):
        try:
            compile(code, filename, "exec")
            return True, ""
        except SyntaxError as e:
            msg = f"{e.__class__.__name__}: {e}"
            logger.error(
                "Error during python syntax validation for %s: %s",
                filename,
                msg,
            )
            return False, msg

    # --- JavaScript / TypeScript ---
    if lang_l in ("javascript", "js", "typescript", "ts"):
        if not _is_tool_available("node"):
            logger.info("Node.js not available; skipping JS/TS syntax validation.")
            return True, "node not available; skipped."

        try:
            with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False) as tmp:
                tmp.write(code)
                tmp_path = tmp.name
            # node --check <file>
            proc = subprocess.run(
                ["node", "--check", tmp_path],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            os.unlink(tmp_path)
            if proc.returncode == 0:
                return True, ""
            return False, proc.stderr.strip() or proc.stdout.strip()
        except Exception as e:
            logger.error(
                "Error during JS/TS syntax validation for %s: %s",
                filename,
                e,
            )
            return False, str(e)

    # --- Java ---
    if lang_l == "java":
        if not _is_tool_available("javac"):
            logger.info("javac not available; skipping Java syntax validation.")
            return True, "javac not available; skipped."

        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                src_path = os.path.join(tmpdir, filename or "Main.java")
                with open(src_path, "w", encoding="utf-8") as f:
                    f.write(code)
                proc = subprocess.run(
                    ["javac", src_path],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                )
                if proc.returncode == 0:
                    return True, ""
                return False, proc.stderr.strip() or proc.stdout.strip()
        except Exception as e:
            logger.error(
                "Error during Java syntax validation for %s: %s",
                filename,
                e,
            )
            return False, str(e)

    # --- Go ---
    if lang_l == "go":
        if not _is_tool_available("go"):
            logger.info("Go toolchain not available; skipping Go syntax validation.")
            return True, "go not available; skipped."

        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                src_path = os.path.join(tmpdir, filename or "main.go")
                with open(src_path, "w", encoding="utf-8") as f:
                    f.write(code)
                proc = subprocess.run(
                    ["go", "build", src_path],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                )
                if proc.returncode == 0:
                    return True, ""
                return False, proc.stderr.strip() or proc.stdout.strip()
        except Exception as e:
            logger.error(
                "Error during Go syntax validation for %s: %s",
                filename,
                e,
            )
            return False, str(e)

    # --- Fallback for unsupported languages ---
    logger.info(
        "No specific syntax validator for language '%s'; treating '%s' as valid.",
        lang,
        filename,
    )
    return True, "No validator for this language; skipped."


def validate_and_repair_syntax(code: str, language: str, filename: str) -> Dict[str, Any]:
    """
    Validate syntax and attempt auto-repair if validation fails.
    
    This function implements a two-phase approach:
    1. First, try validating the original code
    2. If validation fails, attempt auto-repair and validate again
    
    Args:
        code: The source code to validate
        language: Programming language (e.g., "python", "javascript")
        filename: Name of the file (for context in error messages)
    
    Returns:
        Dictionary with keys:
            - 'valid': bool - Whether the code is syntactically valid
            - 'code': str - Original or repaired code
            - 'error': str or None - Error message if validation failed
            - 'repairs_applied': List[str] - List of repairs that were applied
            - 'auto_repaired': bool - Whether auto-repair was needed and successful
    """
    # Try original code first
    is_valid, error_msg = _validate_syntax(code, language, filename)
    
    if is_valid:
        return {
            'valid': True,
            'code': code,
            'error': None,
            'repairs_applied': [],
            'auto_repaired': False
        }
    
    # Validation failed - try auto-repair
    logger.info(f"Syntax validation failed for {filename}. Attempting auto-repair...")
    
    repair_result = SyntaxAutoRepair.auto_repair(code, language)
    
    if repair_result['was_modified']:
        logger.info(f"Applied {len(repair_result['fixes_applied'])} auto-repairs: {repair_result['fixes_applied']}")
        
        # Validate repaired code
        is_valid_repaired, error_msg_repaired = _validate_syntax(
            repair_result['repaired_code'], 
            language, 
            filename
        )
        
        if is_valid_repaired:
            logger.info(f"✓ Auto-repair successful for {filename}")
            return {
                'valid': True,
                'code': repair_result['repaired_code'],
                'error': None,
                'repairs_applied': repair_result['fixes_applied'],
                'auto_repaired': True
            }
        else:
            logger.warning(f"Auto-repair failed to fix {filename}: {error_msg_repaired}")
    else:
        logger.info("No repairs were applicable for the detected syntax errors")
    
    # Return original validation error
    return {
        'valid': False,
        'code': code,
        'error': error_msg,
        'repairs_applied': [],
        'auto_repaired': False
    }


# ==============================================================================
# --- Production-Ready Code Quality Validation ---
# ==============================================================================


def _detect_stub_patterns(code: str, filename: str) -> Tuple[bool, List[str]]:
    """
    Detect if code contains stub/placeholder patterns indicating incomplete implementation.
    
    MODIFIED: Less aggressive detection that allows test code and simple implementations.
    
    Args:
        code: The code content to analyze
        filename: Name of the file being analyzed
        
    Returns:
        Tuple of (is_stub, list_of_issues):
        - is_stub: True if stub patterns detected
        - list_of_issues: Descriptions of stub patterns found
    """
    issues = []
    
    # Don't validate non-code files
    if filename.lower().endswith(('.md', '.txt', '.json', '.yaml', '.yml', '.toml', '.xml', '.rst')):
        return False, []
    
    # Parse code into lines early for all checks
    lines = code.split('\n')
    non_empty_lines = [line for line in lines if line.strip() and not line.strip().startswith('#')]
    
    # CHANGED: More lenient stub patterns - require multiple indicators
    STUB_PATTERNS = [
        (r'\bTODO\b', "Contains TODO comment"),
        (r'\bFIXME\b', "Contains FIXME comment"),
        (r'\bXXX\b', "Contains XXX comment"),
        (r'\bNOT(?:_|\s+)IMPLEMENTED\b', "Contains NOT_IMPLEMENTED marker"),
        (r'\braise\s+NotImplementedError', "Raises NotImplementedError (stub)"),
    ]
    
    code_lower = code.lower()
    
    # Count stub indicators
    stub_count = 0
    for pattern, description in STUB_PATTERNS:
        matches = re.findall(pattern, code, re.IGNORECASE)
        if matches:
            issues.append(f"{description} (found {len(matches)} occurrence(s))")
            stub_count += len(matches)
    
    # CHANGED: Only flag as stub if multiple strong indicators present
    # Single pass statement or short code is OK for utilities and tests
    if stub_count < 2:
        # Code with 0-1 stub indicators is considered valid
        return False, []
    
    # REMOVED: Overly restrictive checks:
    # - No longer checking for minimal line counts for non-main files  
    # - No longer requiring error handling in all files
    # - No longer requiring imports in all Python files
    # These are too restrictive for test code, utilities, and simple implementations
    
    # Only check main application files for completeness
    if filename.lower() in ('main.py', 'app.py', 'server.py'):
        if len(non_empty_lines) < 10:
            issues.append(f"Main application file is too short ({len(non_empty_lines)} non-empty lines)")
            stub_count += 1
        
        if 'try' not in code_lower and 'except' not in code_lower and len(non_empty_lines) > 20:
            issues.append("Large main file missing error handling")
            stub_count += 1
    
    # Need at least 2 concerning indicators to flag as stub
    is_stub = stub_count >= 2
    return is_stub, issues if is_stub else []


def validate_production_ready(code_files: Dict[str, str]) -> Tuple[bool, str]:
    """
    Validate that generated code is production-ready, not just stub/placeholder code.
    
    This function checks for:
    - Stub patterns (pass, ..., TODO, NotImplementedError)
    - Minimal implementations
    - Missing error handling
    - Placeholder comments
    
    Args:
        code_files: Dictionary mapping filenames to code content
        
    Returns:
        Tuple of (is_valid, error_message):
        - is_valid: True if code appears production-ready
        - error_message: Description of issues if not valid
    """
    all_issues = []
    stub_files = []
    
    for filename, content in code_files.items():
        # Skip error files
        if filename == ERROR_FILENAME:
            continue
            
        is_stub, issues = _detect_stub_patterns(content, filename)
        
        if is_stub:
            stub_files.append(filename)
            file_issues = f"\n[{filename}]"
            for issue in issues:
                file_issues += f"\n  - {issue}"
            all_issues.append(file_issues)
    
    if stub_files:
        error_message = (
            "Generated code contains stub/placeholder implementations.\n"
            "Production-ready code should be complete, with full business logic, "
            "error handling, and no TODO/placeholder comments.\n\n"
            "Issues found:\n"
            + "\n".join(all_issues)
            + "\n\n"
            "RECOMMENDATION: Regenerate with more specific requirements or examples. "
            "Explicitly request complete implementations without placeholders."
        )
        logger.warning("Production-ready validation failed for %d files", len(stub_files))
        return False, error_message
    
    logger.info("Production-ready validation passed for %d files", len(code_files))
    return True, ""


# ==============================================================================
# --- Traceability Annotations ---
# ==============================================================================


def _infer_comment_style(lang: str, filename: str) -> Tuple[str, str]:
    """
    Infers the appropriate comment delimiters based on language or file extension.
    """
    lang_l = (lang or "").lower()
    if lang_l in COMMENT_STYLES:
        return COMMENT_STYLES[lang_l]

    ext = os.path.splitext(filename)[1].lstrip(".").lower()
    return COMMENT_STYLES.get(ext, DEFAULT_COMMENT_STYLE)


def add_traceability_comments(
    code_files: Dict[str, str],
    requirements: Dict[str, Any],
    lang: str,
) -> Dict[str, str]:
    """
    Annotates files with traceability information linking code to requirements.

    Rules:
    - For JSON files:
        - If requirement phrases appear, add a `_traceability` map with REQ IDs.
    - For code files:
        - If requirement phrases appear in file, prepend a comment header:
            CODE TRACEABILITY
            This file implements:
              - REQ-001: ...
    """
    features = [
        f
        for f in (requirements.get("features") or [])
        if isinstance(f, str) and f.strip()
    ]

    # Build stable IDs for each feature
    req_map: Dict[str, str] = {
        f"REQ-{i+1:03d}": text for i, text in enumerate(features)
    }

    updated: Dict[str, str] = {}

    for filename, content in code_files.items():
        # JSON: attach structured metadata
        if filename.lower().endswith(".json"):
            try:
                data = json.loads(content)
            except Exception:
                updated[filename] = content
                continue

            serialized_lower = json.dumps(data).lower()
            trace: Dict[str, str] = {}
            for rid, text in req_map.items():
                if text.lower() in serialized_lower:
                    trace[rid] = text

            if trace and isinstance(data, dict):
                data["_traceability"] = trace
                updated[filename] = json.dumps(data, indent=2)
            else:
                updated[filename] = content
            continue

        # Code files: prepend header if any requirements match
        lower_content = content.lower()
        matched: Dict[str, str] = {
            rid: text for rid, text in req_map.items() if text.lower() in lower_content
        }

        if not matched:
            updated[filename] = content
            continue

        start, end = _infer_comment_style(lang, filename)

        header_lines = [
            f"{start} CODE TRACEABILITY",
            f"{start} This file implements the following requirements:",
        ]
        for rid, text in matched.items():
            header_lines.append(f"{start}  - {rid}: {text}")
        if end:
            header_lines.append(end)

        header_block = "\n".join(header_lines)
        updated[filename] = f"{header_block}\n\n{content}"

    return updated


# ==============================================================================
# --- Security and Monitoring ---
# ==============================================================================


def monitor_and_scan_code(code_files: Dict[str, str]) -> Dict[str, str]:
    """
    Runs lightweight secret detection and delegates to a unified SAST scanner.

    - Does NOT mutate code_files.
    - Emits audit events via log_action.
    """
    # 1. Secret heuristics
    for filename, code in code_files.items():
        if SECRET_REGEX.search(code):
            log_action(
                "Secret Scan Finding",
                {
                    "file": filename,
                    "detail": "Potential secret-like assignment detected "
                    "(heuristic: sensitive variable name).",
                },
            )

    # 2. Unified SAST via scan_for_vulnerabilities
    try:
        results = scan_for_vulnerabilities(code_files)
        total_issues = 0
        findings_summary: Dict[str, int] = {}

        if isinstance(results, dict):
            for fname, info in results.items():
                issues = None
                if isinstance(info, dict):
                    issues = info.get("issues")
                if isinstance(issues, list):
                    count = len(issues)
                    if count:
                        findings_summary[fname] = count
                        total_issues += count

        if total_issues:
            logger.warning(
                "Unified SAST scan completed. Total issues found: %s",
                total_issues,
            )
        else:
            logger.info("Unified SAST scan completed. No issues found.")

        log_action(
            "Unified SAST Scan Complete",
            {
                "total_issues": total_issues,
                "files_scanned": len(code_files),
                "finding_summary": findings_summary,
            },
        )

    except Exception as e:
        logger.error("Error during unified SAST scan: %s", e)
        log_action(
            "Unified SAST Scan Error",
            {
                "error": str(e),
                "files_scanned": len(code_files),
            },
        )

    return code_files


# NOTE:
# The older helper `_run_sast_tool` and related imports have been intentionally
# removed. All external security analysis should be funneled through
# `scan_for_vulnerabilities` provided by the runner layer.
