# -*- coding: utf-8 -*-
"""
Production-Ready Code Generation Post-Processor

This module parses, validates, annotates, and scans code generated by an LLM.

Capabilities:
- Multi-file JSON response parsing with single-file fallback.
- Language-aware syntax validation (Python, JS/TS, Java, Go) using native tools.
- Secret scanning via heuristics.
- Unified SAST integration via `scan_for_vulnerabilities` from runner utilities.
- Requirements-to-code traceability annotations.
- Safe degradation when external tools or runner utilities are unavailable.
"""

from __future__ import annotations

import json
import logging
import os
import re
import subprocess
import tempfile
from functools import lru_cache
from typing import Any, Dict, Tuple

logger = logging.getLogger(__name__)

# ==============================================================================
# --- Runner / Environment Integration ---
# ==============================================================================

try:  # Prefer real runner logging if available
    # --- FIX: Changed import to be relative ---
    from ...runner.runner_logging import log_audit_event as _runner_log_audit_event
except ImportError:  # Fallback stub
    def _runner_log_audit_event(event_type: str, payload: Dict[str, Any] | None = None) -> None:
        logger.warning(
            "Using dummy log_audit_event (runner not available). "
            "event_type=%s payload=%s",
            event_type,
            payload,
        )


try:  # Prefer real security utilities if available
    # --- FIX: Changed import to be relative ---
    from ...runner.runner_security_utils import scan_for_vulnerabilities as _runner_scan_for_vulnerabilities
except ImportError:  # Fallback stub
    def _runner_scan_for_vulnerabilities(code_files: Dict[str, str]) -> Dict[str, Any]:
        logger.warning(
            "Using dummy scan_for_vulnerabilities (runner not available). "
            "No SAST issues will be reported."
        )
        return {}


import inspect


def log_audit_event(event_type: str, payload: Dict[str, Any] | None = None) -> None:
    """
    Direct wrapper so we have a stable entrypoint in this module.

    Handles both sync and async implementations of the underlying logger
    without causing 'coroutine was never awaited' warnings in sync contexts.
    """
    payload = payload or {}
    fn = _runner_log_audit_event
    try:
        if inspect.iscoroutinefunction(fn):
            # We are in a sync context; don't create an un-awaited coroutine.
            logger.warning(
                "Async log_audit_event detected; skipping await in sync context. "
                "event_type=%s payload=%s",
                event_type,
                payload,
            )
            return
        fn(event_type, payload)
    except Exception:  # pragma: no cover - logging failures must never break main flow
        logger.exception("Failed to emit audit event: %s", event_type)


def log_action(event_type: str, payload: Dict[str, Any] | None = None) -> None:
    """
    Alias used throughout this module and by tests.
    """
    log_audit_event(event_type, payload)


def scan_for_vulnerabilities(code_files: Dict[str, str]) -> Dict[str, Any]:
    """
    Wrapper for runner-based SAST.

    Returns a dict structure:
        { filename: { "issues": [ ... ] }, ... }
    """
    try:
        return _runner_scan_for_vulnerabilities(code_files)
    except Exception:  # pragma: no cover - defensive
        logger.exception("scan_for_vulnerabilities failed unexpectedly.")
        return {}


# ==============================================================================
# --- Constants ---
# ==============================================================================

DEFAULT_FILENAME = "main.py"
ERROR_FILENAME = "error.txt"

# Very lightweight heuristic: any assignment to a suspicious name is flagged.
SECRET_REGEX = re.compile(
    r"(api_key|apikey|secret|token|password)\s*=",
    re.IGNORECASE,
)

# Language-specific comment styles for traceability
COMMENT_STYLES: Dict[str, Tuple[str, str]] = {
    # lang or extension : (start, end)
    "python": ("#", ""),
    "py": ("#", ""),
    "javascript": ("//", ""),
    "js": ("//", ""),
    "typescript": ("//", ""),
    "ts": ("//", ""),
    "java": ("//", ""),
    "csharp": ("//", ""),
    "cs": ("//", ""),
    "go": ("//", ""),
    "rust": ("//", ""),
    "rs": ("//", ""),
    "ruby": ("#", ""),
    "rb": ("#", ""),
    "php": ("//", ""),
    "swift": ("//", ""),
    "kotlin": ("//", ""),
    "kt": ("//", ""),
    "css": ("/*", "*/"),
    "sql": ("--", ""),
}

DEFAULT_COMMENT_STYLE = ("#", "")


# ==============================================================================
# --- Tooling Helpers ---
# ==============================================================================

@lru_cache(maxsize=None)
def _is_tool_available(tool: str) -> bool:
    """
    Checks if an executable is available on PATH. Cached for efficiency.
    """
    from shutil import which

    available = which(tool) is not None
    logger.debug("Tool availability check: %s -> %s", tool, available)
    return available


# ==============================================================================
# --- Core: LLM Response Parsing ---
# ==============================================================================

def parse_llm_response(response: str, lang: str = "python") -> Dict[str, str]:
    """
    Parses the LLM response, handling both multi-file JSON and single-file code.

    Multi-file mode expects:
        {
          "files": {
            "main.py": "<code>",
            "util.py": "<code>"
          }
        }

    Behavior:
    - For multi-file JSON:
        - Each file is cleaned and syntax-validated.
        - Valid files are returned as-is.
        - Invalid files are summarized into ERROR_FILENAME.
    - For non-JSON:
        - Treat as a single file; validate.
        - Return DEFAULT_FILENAME or ERROR_FILENAME accordingly.
    """
    raw = response.strip()
    # For robustness, strip outer code fences before JSON parsing attempt.
    cleaned_for_json = _clean_code_block(raw)

    # --- 1. Try multi-file JSON format ---
    try:
        payload = json.loads(cleaned_for_json)
        if isinstance(payload, dict) and isinstance(payload.get("files"), dict):
            files_obj = payload["files"]
            code_files: Dict[str, str] = {}
            errors: Dict[str, str] = {}

            for filename, content in files_obj.items():
                if not isinstance(content, str):
                    errors[filename] = "Content is not a string."
                    continue

                cleaned = _clean_code_block(content)
                is_valid, msg = _validate_syntax(cleaned, lang, filename)

                if is_valid:
                    code_files[filename] = cleaned
                else:
                    logger.warning(
                        "Syntax validation failed for '%s' (%s). Details: %s",
                        filename,
                        lang,
                        msg,
                    )
                    errors[filename] = msg

            # If any file failed, emit an aggregated error.txt
            if errors:
                lines = [
                    "One or more files failed syntax validation.",
                    "",
                ]
                for fname, emsg in errors.items():
                    lines.append(f"[{fname}]")
                    lines.append(str(emsg))
                    lines.append("")
                code_files[ERROR_FILENAME] = "\n".join(lines).rstrip()

            if code_files:
                log_action(
                    "Parsed Multi-File Response",
                    {
                        "files": [f for f in code_files.keys() if f != ERROR_FILENAME],
                        "language": lang,
                        "had_errors": bool(errors),
                    },
                )
                return code_files
            # If nothing usable, fall through to single-file handling.

    except json.JSONDecodeError:
        logger.info("LLM response is not valid JSON; using single-file fallback.")
    except Exception as e:
        logger.error("Unexpected error while parsing JSON LLM response: %s", e)

    # --- 2. Single-file fallback ---
    cleaned_code = _clean_code_block(raw)
    is_valid, msg = _validate_syntax(cleaned_code, lang, DEFAULT_FILENAME)

    if is_valid:
        log_action(
            "Parsed Single-File Response",
            {"file": DEFAULT_FILENAME, "language": lang},
        )
        return {DEFAULT_FILENAME: cleaned_code}

    logger.error(
        "Syntax validation failed for single-file response (%s). Details: %s",
        lang,
        msg,
    )
    error_content = (
        f"Generated code failed syntax validation for language '{lang}'.\n\n"
        f"Validation Tool Output:\n{msg}"
    )
    return {ERROR_FILENAME: error_content}


# ==============================================================================
# --- Helpers: Cleaning & Syntax Validation ---
# ==============================================================================

def _clean_code_block(code_content: str) -> str:
    """
    Removes markdown-style code fences from a string if present.

    Handles patterns like:
        ```python
        code
        ```
    and falls back gracefully if no fences exist.
    """
    text = code_content.strip()
    # Strict fenced match
    fenced_pattern = r"^\s*```[a-zA-Z0-9_+-]*\n(.*?)\n```\\s*$"
    m = re.search(fenced_pattern, text, flags=re.DOTALL)
    if m:
        return m.group(1).strip()

    # More permissive removal of leading/trailing fences
    if text.startswith("```") and "```" in text[3:]:
        # Strip first line (```lang?) and last ``` line
        lines = text.splitlines()
        # remove first and last fence-like lines
        if lines:
            lines = lines[1:]
        while lines and lines[-1].strip().startswith("```"):
            lines = lines[:-1]
        return "\n".join(lines).strip()

    return text


def _validate_syntax(code: str, lang: str, filename: str) -> Tuple[bool, str]:
    """
    Validates code syntax using language-appropriate mechanisms.

    Returns:
        (is_valid, message)
        - is_valid: True if considered syntactically OK.
        - message: empty or diagnostic text.
    """
    lang_l = (lang or "").lower()

    if not code.strip():
        logger.warning("Empty code block for %s; treating as valid.", filename)
        return True, "Empty code treated as valid."

    # --- Python ---
    if lang_l in ("python", "py"):
        try:
            compile(code, filename, "exec")
            return True, ""
        except SyntaxError as e:
            msg = f"{e.__class__.__name__}: {e}"
            logger.error(
                "Error during python syntax validation for %s: %s",
                filename,
                msg,
            )
            return False, msg

    # --- JavaScript / TypeScript ---
    if lang_l in ("javascript", "js", "typescript", "ts"):
        if not _is_tool_available("node"):
            logger.info("Node.js not available; skipping JS/TS syntax validation.")
            return True, "node not available; skipped."

        try:
            with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False) as tmp:
                tmp.write(code)
                tmp_path = tmp.name
            # node --check <file>
            proc = subprocess.run(
                ["node", "--check", tmp_path],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            os.unlink(tmp_path)
            if proc.returncode == 0:
                return True, ""
            return False, proc.stderr.strip() or proc.stdout.strip()
        except Exception as e:
            logger.error(
                "Error during JS/TS syntax validation for %s: %s",
                filename,
                e,
            )
            return False, str(e)

    # --- Java ---
    if lang_l == "java":
        if not _is_tool_available("javac"):
            logger.info("javac not available; skipping Java syntax validation.")
            return True, "javac not available; skipped."

        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                src_path = os.path.join(tmpdir, filename or "Main.java")
                with open(src_path, "w", encoding="utf-8") as f:
                    f.write(code)
                proc = subprocess.run(
                    ["javac", src_path],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                )
                if proc.returncode == 0:
                    return True, ""
                return False, proc.stderr.strip() or proc.stdout.strip()
        except Exception as e:
            logger.error(
                "Error during Java syntax validation for %s: %s",
                filename,
                e,
            )
            return False, str(e)

    # --- Go ---
    if lang_l == "go":
        if not _is_tool_available("go"):
            logger.info("Go toolchain not available; skipping Go syntax validation.")
            return True, "go not available; skipped."

        try:
            with tempfile.TemporaryDirectory() as tmpdir:
                src_path = os.path.join(tmpdir, filename or "main.go")
                with open(src_path, "w", encoding="utf-8") as f:
                    f.write(code)
                proc = subprocess.run(
                    ["go", "build", src_path],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                )
                if proc.returncode == 0:
                    return True, ""
                return False, proc.stderr.strip() or proc.stdout.strip()
        except Exception as e:
            logger.error(
                "Error during Go syntax validation for %s: %s",
                filename,
                e,
            )
            return False, str(e)

    # --- Fallback for unsupported languages ---
    logger.info(
        "No specific syntax validator for language '%s'; treating '%s' as valid.",
        lang,
        filename,
    )
    return True, "No validator for this language; skipped."


# ==============================================================================
# --- Traceability Annotations ---
# ==============================================================================

def _infer_comment_style(lang: str, filename: str) -> Tuple[str, str]:
    """
    Infers the appropriate comment delimiters based on language or file extension.
    """
    lang_l = (lang or "").lower()
    if lang_l in COMMENT_STYLES:
        return COMMENT_STYLES[lang_l]

    ext = os.path.splitext(filename)[1].lstrip(".").lower()
    return COMMENT_STYLES.get(ext, DEFAULT_COMMENT_STYLE)


def add_traceability_comments(
    code_files: Dict[str, str],
    requirements: Dict[str, Any],
    lang: str,
) -> Dict[str, str]:
    """
    Annotates files with traceability information linking code to requirements.

    Rules:
    - For JSON files:
        - If requirement phrases appear, add a `_traceability` map with REQ IDs.
    - For code files:
        - If requirement phrases appear in file, prepend a comment header:
            CODE TRACEABILITY
            This file implements:
              - REQ-001: ...
    """
    features = [
        f for f in (requirements.get("features") or [])
        if isinstance(f, str) and f.strip()
    ]

    # Build stable IDs for each feature
    req_map: Dict[str, str] = {
        f"REQ-{i+1:03d}": text for i, text in enumerate(features)
    }

    updated: Dict[str, str] = {}

    for filename, content in code_files.items():
        # JSON: attach structured metadata
        if filename.lower().endswith(".json"):
            try:
                data = json.loads(content)
            except Exception:
                updated[filename] = content
                continue

            serialized_lower = json.dumps(data).lower()
            trace: Dict[str, str] = {}
            for rid, text in req_map.items():
                if text.lower() in serialized_lower:
                    trace[rid] = text

            if trace and isinstance(data, dict):
                data["_traceability"] = trace
                updated[filename] = json.dumps(data, indent=2)
            else:
                updated[filename] = content
            continue

        # Code files: prepend header if any requirements match
        lower_content = content.lower()
        matched: Dict[str, str] = {
            rid: text
            for rid, text in req_map.items()
            if text.lower() in lower_content
        }

        if not matched:
            updated[filename] = content
            continue

        start, end = _infer_comment_style(lang, filename)

        header_lines = [
            f"{start} CODE TRACEABILITY",
            f"{start} This file implements the following requirements:",
        ]
        for rid, text in matched.items():
            header_lines.append(f"{start}  - {rid}: {text}")
        if end:
            header_lines.append(end)

        header_block = "\n".join(header_lines)
        updated[filename] = f"{header_block}\n\n{content}"

    return updated


# ==============================================================================
# --- Security and Monitoring ---
# ==============================================================================

def monitor_and_scan_code(code_files: Dict[str, str]) -> Dict[str, str]:
    """
    Runs lightweight secret detection and delegates to a unified SAST scanner.

    - Does NOT mutate code_files.
    - Emits audit events via log_action.
    """
    # 1. Secret heuristics
    for filename, code in code_files.items():
        if SECRET_REGEX.search(code):
            log_action(
                "Secret Scan Finding",
                {
                    "file": filename,
                    "detail": "Potential secret-like assignment detected "
                              "(heuristic: sensitive variable name).",
                },
            )

    # 2. Unified SAST via scan_for_vulnerabilities
    try:
        results = scan_for_vulnerabilities(code_files)
        total_issues = 0
        findings_summary: Dict[str, int] = {}

        if isinstance(results, dict):
            for fname, info in results.items():
                issues = None
                if isinstance(info, dict):
                    issues = info.get("issues")
                if isinstance(issues, list):
                    count = len(issues)
                    if count:
                        findings_summary[fname] = count
                        total_issues += count

        if total_issues:
            logger.warning(
                "Unified SAST scan completed. Total issues found: %s",
                total_issues,
            )
        else:
            logger.info("Unified SAST scan completed. No issues found.")

        log_action(
            "Unified SAST Scan Complete",
            {
                "total_issues": total_issues,
                "files_scanned": len(code_files),
                "finding_summary": findings_summary,
            },
        )

    except Exception as e:
        logger.error("Error during unified SAST scan: %s", e)
        log_action(
            "Unified SAST Scan Error",
            {
                "error": str(e),
                "files_scanned": len(code_files),
            },
        )

    return code_files


# NOTE:
# The older helper `_run_sast_tool` and related imports have been intentionally
# removed. All external security analysis should be funneled through
# `scan_for_vulnerabilities` provided by the runner layer.