[pytest]
pythonpath = .
markers =
    unit: mark a test as a unit test
    asyncio: mark a test as async
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore:prometheus_client version.*:UserWarning
    ignore:pkg_resources is deprecated:DeprecationWarning
    ignore:Deprecated call to `pkg_resources.declare_namespace.*:DeprecationWarning
    ignore:Duplicated timeseries in CollectorRegistry.*:UserWarning