# Copyright © 2025 Novatrax Labs LLC. All Rights Reserved.

apiVersion: v1
kind: Namespace
metadata:
  name: codefactory-production
  labels:
    name: codefactory-production
    app: codefactory
    environment: production
