# Copyright © 2025 Novatrax Labs LLC. All Rights Reserved.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: codefactory

resources:
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - api-deployment.yaml
  - redis-deployment.yaml
  - ingress.yaml
  - api-networkpolicy.yaml
  - redis-networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/name: codefactory
      app.kubernetes.io/part-of: codefactory-platform

images:
  - name: ghcr.io/musicmonk42/codefactory
    newTag: latest
