# Copyright © 2025 Novatrax Labs LLC. All Rights Reserved.

apiVersion: v1
kind: Namespace
metadata:
  name: codefactory-staging
  labels:
    name: codefactory-staging
    app: codefactory
    environment: staging
